Added link and personal page
sleddog/methods-spring-2023 pull request #11
Opened 2023-02-07 23:58 UTC by coryjanes

2023-02-08 00:26 UTC, Tech-Wizz requested changes
for the index part just do ./name.html

also, do a pull or merge them with the changes made

2023-02-14 23:36 UTC, zdjewett approved these changes

2023-02-14 23:51 UTC, coryjanes reviewed
Fixed link and added music page with link

2023-02-15 00:12 UTC, Tech-Wizz approved these changes
Looks good but you should have a separate branch for yourself and your topic/topics

2023-02-15 05:11 UTC, merged