FizzBuzz
sleddog/methods-spring-2023 pull request #67
Opened 2023-03-08 00:04 UTC by coryjanes

Added FizzBuzz needed files

2023-03-08 03:23 UTC, Tech-Wizz requested changes
You forgot about the FizzBuzz for 15 since it is a 3 and a 5.  I only got Fizz.

2023-03-21 03:41 UTC, Tech-Wizz commented
For got to show evidence of my running the code (+10)
![FizzBuzzCory](https://user-images.githubusercontent.com/55522241/226512547-a5961b81-7c4f-4d9d-ae45-458684ba5fd6.png)

2023-03-21 19:03 UTC, JamesLucas943 commented
![image](https://user-images.githubusercontent.com/56455079/226713244-a1f0ec97-fdb0-4359-850a-7b57c25a4156.png)

Same thing as Tech-Wizz. The code runs great, but you need to make sure that for numbers that are divisible by both 3 and 5 'FizzBuzz' is printed rather than just 'Fizz'. Everything else looks great.

2023-03-22 04:32 UTC, Tech-Wizz approved these changes

2023-03-22 04:32 UTC, Tech-Wizz commented on fizzbuzz/python/coryjanes/fizzbuzz.py
Runs correctly now. Pulled down to my machine and it runs. +10

2023-03-28 21:01 UTC, merged