Fizzbuzz/python/andrew
sleddog/methods-spring-2023 pull request #69
Opened 2023-03-08 04:55 UTC by corrosivecamel

Adding my name to index.html and adding FizzBuzz directory.

2023-03-09 18:01 UTC, corrosivecamel commented
Thats what it does

2023-03-09 20:23 UTC, darshandiamond reviewed
I think the program works fine, but the shell script does ask for a number instead of just typing ./run.sh 17 and getting the output.   I don't know if that was required, but otherwise if looked good to me.

2023-03-09 21:07 UTC, Skeegan123 commented
> I think the program works fine, but the shell script does ask for a number instead of just typing ./run.sh 17 and getting the output.   I don't know if that was required, but otherwise if looked good to me. 

This is what I meant, also not 100% sure this is required but it seems like this is what is preferred

2023-03-09 23:06 UTC, corrosivecamel commented
Ah gotcha. I didn't understand before, but I see what you're saying now.

2023-03-13 03:10 UTC, cameronwilcox commented
+1 script + code does appear to work, though I would definitely recommend the changes discussed above.

2023-03-21 03:56 UTC, Tech-Wizz requested changes
If you can review the small issues you are golden

2023-03-21 03:56 UTC, Tech-Wizz commented on fizzbuzz/index.html
This link you added does not go anywhere and you are missing the instructions in HTML format. I believe this is where this is supposed to go? Also on top of this, you have your code in a fizzbuzz folder in a fizzbuzz folder. I believe the format is like how you linked to your missing webpage.

2023-03-21 03:56 UTC, Tech-Wizz commented on fizzbuzz/fizzbuzz/run.sh
I agree with Keegan. The format is supposed to work from git bash so we can't really select a file we just run it in a terminal. It still works so the fizzbuzz is complete

2023-03-27 22:22 UTC, closed without merging