Cameron wilcox fizzbuzz plus plus
sleddog/methods-spring-2023 pull request #79
Opened 2023-03-30 16:35 UTC by cameronwilcox

Pull request for Cameron Wilcox, having added to Cory Janes program.

2023-03-31 14:18 UTC, Skeegan123 reviewed
I would recommend splitting your unit tests into their own tests i.e. a test for 3, a test for 5, a test for 7, and a test for 11. I did the same thing originally but the rubric says "unit tests" so there is probably supposed to be multiple. Let me know if that makes sense. Other than that it looks pretty good. I will try running it when you make that change.

2023-03-31 18:20 UTC, cameronwilcox commented
@Skeegan123 Made the changes, let me know if I should change anything else.

2023-03-31 20:41 UTC, Skeegan123 reviewed
+1 Looks good. I will pull it down and test it

2023-03-31 20:50 UTC, Skeegan123 requested changes
A couple things, 1. Could you try changing the run.sh from python to python3 and see if it works on your computer? That way it will work on macs too since from what I've seen most macs need it to be python3 and that usually works on windows as well. And 2. Could you try adding the permissions to test.sh and run.sh then commiting them? If you already did its whatever but for me I had to add the permissions myself.

2023-03-31 20:53 UTC, sleddog commented on fizzbuzz/python/coryjanes/fizzbuzz.py
> +	if number % 5 != 0 and number % 3 != 0 and number % 7 != 0 and number % 11 != 0:
could simplify this and check to see: `if to_print == ""`

2023-04-03 21:48 UTC, cameronwilcox commented
@Skeegan123 I should have updated the permissions, let me know if it works for you.

2023-04-03 21:54 UTC, Skeegan123 approved these changes
+10 Looks good and runs properly with the correct permisions and simplified if statement

2023-04-04 18:57 UTC, merged